//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSPS.CustomFunctoids {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SSPS_CustomFunctoidsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SSPS_CustomFunctoidsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSPS.CustomFunctoids.SSPS_CustomFunctoidsResources", typeof(SSPS_CustomFunctoidsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap CTG_BITMAP {
            get {
                object obj = ResourceManager.GetObject("CTG_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts an Ordinal date to a standard date format. This functoid requires 2 inputs:  first, the date (in CCYYddd format); second the format for the output date..
        /// </summary>
        internal static string CTG_DESC {
            get {
                return ResourceManager.GetString("CTG_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Ordinal Date.
        /// </summary>
        internal static string CTG_NAME {
            get {
                return ResourceManager.GetString("CTG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts a date from Ordinal format.
        /// </summary>
        internal static string CTG_TOOLTIP {
            get {
                return ResourceManager.GetString("CTG_TOOLTIP", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CTO_BITMAP {
            get {
                object obj = ResourceManager.GetObject("CTO_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts a valid date to the ordinal format of CCYYddd.  This functoid requires 2 inputs:  first, the date; second format of the input date..
        /// </summary>
        internal static string CTO_DESC {
            get {
                return ResourceManager.GetString("CTO_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Ordinal Date.
        /// </summary>
        internal static string CTO_NAME {
            get {
                return ResourceManager.GetString("CTO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts a date to Ordinal format.
        /// </summary>
        internal static string CTO_TOOLTIP {
            get {
                return ResourceManager.GetString("CTO_TOOLTIP", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CUSTURI_BITMAP {
            get {
                object obj = ResourceManager.GetObject("CUSTURI_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs a database lookup based on the customer ID.  This functoid requires one input, which is the customer ID..
        /// </summary>
        internal static string CUSTURI_DESC {
            get {
                return ResourceManager.GetString("CUSTURI_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Customer URI.
        /// </summary>
        internal static string CUSTURI_NAME {
            get {
                return ResourceManager.GetString("CUSTURI_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a customer URI.
        /// </summary>
        internal static string CUSTURI_TOOLTIP {
            get {
                return ResourceManager.GetString("CUSTURI_TOOLTIP", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FMT_DATE_BITMAP {
            get {
                object obj = ResourceManager.GetObject("FMT_DATE_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts a valid date from one format to another.  This functoid requires 3 inputs:  first, the date; second the input date format; third the output date format..
        /// </summary>
        internal static string FMT_DATE_DESC {
            get {
                return ResourceManager.GetString("FMT_DATE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Date Conversion.
        /// </summary>
        internal static string FMT_DATE_NAME {
            get {
                return ResourceManager.GetString("FMT_DATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts a date from one format to another.
        /// </summary>
        internal static string FMT_DATE_TOOLTIP {
            get {
                return ResourceManager.GetString("FMT_DATE_TOOLTIP", resourceCulture);
            }
        }
    }
}
